name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Check out code
      uses: actions/checkout@v1
    - name: npm install, build, and test
      run: |
        npm run build --if-present
        npm run lint
      env:
        CI: true
